language: go
go:
- 1.12
os:
- linux
env:
- GO111MODULE=on
script:
- make release
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: C6zjwbTGgjhGgPUiqCJGNUP4UPzCSEO6US5Auc26Opt+V2ShUbZ2V4Ue/MfcwbDIExnYVjeqCE49uhP0ZvzxCamaSOzkbBkQjj/z3AytGKSL3s2WRHFuVOHoCP5GAovNxzfnxKlZpHO5O5gDXKZGiiVaOZX+8EjrIPwFyV31D3vm2awUCY6n/JEV9uxvVwcwSjbZcmqp2eihuQwh3sy2FzXnMedUbSUrg+l+TZGLgAJzrHXy3pedMoGQ01s9i65IeWyu0UtmT9kccN+NjTR+p3cl4Hvu9HzNLIYQCN/4ByKAMyaYMO0ILcSbBWzHRo31WLAvLDt5jL+d99CIi/rAcUDjDijZ2G/Do0ve5mSUOUzpGKx06ZfCLaNrjOt+QCK2IuCGRrfLVd5pdIFbd9VouRWgLmijUTMcDU+BaFLzjJgrfMr1Jljf6iXktDXDppRxxDUVgJnDhdCmHhwTKxWzqZ0Zqm0yIQi//lrIFwKM/d3AaEw/hsaR2k9no36/PlGLW5yvfwvA4aWd3qZi01jHGyREIEZRRKVkKV4fxUL0KMM8c981vQ+kOuQza/FxTIRMY37DdDrprRgVZrvKP/67F/ypTCrA34y+iKJTTdW71Gy8P1LdOInL6v2FdvPNjijfo52/m02AVf1YI+IcgfBw3XXwSrZAlTiNoq/31l/voKQ=
  file_glob: true
  file: output/terraform-provider-jira*.zip
  on:
    tags: true
    repo: fourplusone/terraform-provider-jira
