language: go
go:
- 1.11.1
os:
- linux
script:
- make release
deploy:
  provider: releases
  api_key:
    secure: YI3P2sYCzbpAnbcC9hLO60+tfTw9oRMDIm4NukszTD0Bk97T3U/IYQ3YUNI09xoUmuaWQwHcEGYw66ObB07yIt+3iwKm5IZpx+Niv1cUAewUTjouRUk1dvkxjAQWr9UVjXsi/IO6t903c3fx6yrkvnBqAPqqXnnOXyT8cv1P7zrPX3QmBPJ4zYWkoR0wJnNAI/x+mF1Dfbbt7GtMR0QRYCGY0Dq2TPu3PQPJZKSi4X2JRTmxO1NsMg2WcJbuFnJ7tslBFz4KhRW0Jp7Arr9EwisAJF04oJJjGXvvgZEAGdAIvYDu1SFwp7A+9ONiyLZWSBwumFv6zN0TYknml7Iku4PPWz/TOCZ3PR+rVWSKjcA+5cOAEx9kRQii2sZWc7Jd1IW/8afaXfIPUeYb/A68xPzNBpZ4Yy9wyShZz/As6er3OtdhPimIA4ld61/iM0PZC9CHCAQhN6v8Jt47sPMRtEJWo4q4j/SIXE7Co/MGISSpDxnYk46RSrW1jiHFw2f4w71U2O0NEIv67q87tA44y4W8yB+jfYCnzK5YkOonxXz4G6TVKTw4PEC7tbotRhS2HKLzY8/LpxNt3TqetEebkC6ugKIXQMzHPMeRB7jv9udvf+L+27YRYf0PTWSe7zgmSiKla0rzqxr4IMxDUjfwFRXTR/Bw+NSDvvEjdeanAbo=
  file_glob: true
  file: output/terraform-provider-jira*.zip
  on:
    tags: true
    repo: fourplusone/terraform-provider-jira
