name: Build & Tests

on:
  workflow_dispatch
  #push:
  #  branches: [ main, ci-testing ]
  #pull_request:
  #  branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.18
    - name: Build
      run: make build
  test:
   services:
     jira:
       image: docker.pkg.github.com/fourplusone/docker-atlas/jira:latest
       options: --tty --health-start-period=10m
       credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
       ports:
       - 2990:2990
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v4

   - name: Set up Go
     uses: actions/setup-go@v5
     with:
       go-version: 1.18

   - name: Test
     env:
       JIRA_URL: http://localhost:2990/jira/
       JIRA_USER: admin
       JIRA_PASSWORD: admin
     run: make test
